2024-10-12 16:45:28.711132: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
2024-10-12 16:45:28.711129: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
2024-10-12 16:46:10.190100: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-10-12 16:46:10.190100: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-10-12 16:46:10.194522: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcuda.so.1
2024-10-12 16:46:10.194523: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcuda.so.1
2024-10-12 16:46:10.238642: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties: 
pciBusID: 0000:c1:00.0 name: NVIDIA GeForce RTX 3090 computeCapability: 8.6
coreClock: 1.695GHz coreCount: 82 deviceMemorySize: 23.69GiB deviceMemoryBandwidth: 871.81GiB/s
2024-10-12 16:46:10.238642: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties: 
pciBusID: 0000:c1:00.0 name: NVIDIA GeForce RTX 3090 computeCapability: 8.6
coreClock: 1.695GHz coreCount: 82 deviceMemorySize: 23.69GiB deviceMemoryBandwidth: 871.81GiB/s
2024-10-12 16:46:10.239044: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
2024-10-12 16:46:10.239043: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
2024-10-12 16:46:10.476453: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublas.so.11
2024-10-12 16:46:10.476538: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublasLt.so.11
2024-10-12 16:46:10.476642: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublas.so.11
2024-10-12 16:46:10.476704: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublasLt.so.11
2024-10-12 16:46:10.648506: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcufft.so.10
2024-10-12 16:46:10.648674: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcufft.so.10
2024-10-12 16:46:10.806824: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcurand.so.10
2024-10-12 16:46:10.806836: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcurand.so.10
2024-10-12 16:46:11.182625: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcusolver.so.11
2024-10-12 16:46:11.182664: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcusolver.so.11
2024-10-12 16:46:11.235856: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcusparse.so.11
2024-10-12 16:46:11.235988: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcusparse.so.11
2024-10-12 16:46:11.288063: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudnn.so.8
2024-10-12 16:46:11.288081: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudnn.so.8
2024-10-12 16:46:11.290127: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
2024-10-12 16:46:11.290155: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
2024-10-12 16:46:11.290159: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
2024-10-12 16:46:11.290179: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
2024-10-12 16:46:12.038844: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2024-10-12 16:46:12.038906: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      0 
2024-10-12 16:46:12.038913: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 0:   N 
2024-10-12 16:46:12.040494: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1418] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 21899 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce RTX 3090, pci bus id: 0000:c1:00.0, compute capability: 8.6)
TensorFlow:  2.5
Model:       resnet50
Dataset:     imagenet (synthetic)
Mode:        BenchmarkMode.TRAIN
SingleSess:  False
Batch size:  40 global
             40.0 per device
Num batches: 100
Num epochs:  0.00
Devices:     ['/gpu:0']
Data format: NCHW
Optimizer:   sgd
Variables:   parameter_server
==========
2024-10-12 16:46:12.060373: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2024-10-12 16:46:12.060430: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      0 
2024-10-12 16:46:12.060437: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 0:   N 
2024-10-12 16:46:12.062021: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1418] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 21893 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce RTX 3090, pci bus id: 0000:c1:00.0, compute capability: 8.6)
TensorFlow:  2.5
Model:       resnet50
Dataset:     imagenet (synthetic)
Mode:        BenchmarkMode.TRAIN
SingleSess:  False
Batch size:  40 global
             40.0 per device
Num batches: 100
Num epochs:  0.00
Devices:     ['/gpu:0']
Data format: NCHW
Optimizer:   sgd
Variables:   parameter_server
==========
Generating training model
Generating training model
shapes: self.top_layer: [40, 3, 224, 224]
shapes: network.top_layer 1: [40, 3, 224, 224]
shapes: self.top_layer: [40, 3, 224, 224]
shapes: network.top_layer 1: [40, 3, 224, 224]
shapes: network.top_layer 2: [40, 3, 224, 224]
shapes: network.top_layer 2: [40, 3, 224, 224]
2024-10-12 16:46:12.128345: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties: 
pciBusID: 0000:c1:00.0 name: NVIDIA GeForce RTX 3090 computeCapability: 8.6
coreClock: 1.695GHz coreCount: 82 deviceMemorySize: 23.69GiB deviceMemoryBandwidth: 871.81GiB/s
2024-10-12 16:46:12.128318: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties: 
pciBusID: 0000:c1:00.0 name: NVIDIA GeForce RTX 3090 computeCapability: 8.6
coreClock: 1.695GHz coreCount: 82 deviceMemorySize: 23.69GiB deviceMemoryBandwidth: 871.81GiB/s
2024-10-12 16:46:12.130081: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
2024-10-12 16:46:12.130121: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
WARNING:tensorflow:From /HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/keras/layers/normalization.py:534: _colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From /HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/keras/layers/normalization.py:534: _colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
W1012 16:46:12.151200 47294311533952 deprecation.py:330] From /HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/keras/layers/normalization.py:534: _colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
W1012 16:46:12.151200 47465832639872 deprecation.py:330] From /HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/keras/layers/normalization.py:534: _colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
cnn.top_layer.shape: [40, 64, 56, 256]
cnn.top_layer.shape: [40, 64, 56, 256]
cnn.top_layer.shape: [40, 64, 56, 256]
cnn.top_layer.shape: [40, 64, 56, 256]
cnn.top_layer.shape: [40, 64, 56, 256]
cnn.top_layer.shape: [40, 64, 56, 256]
cnn.top_layer.shape: [40, 32, 28, 512]
cnn.top_layer.shape: [40, 32, 28, 512]
cnn.top_layer.shape: [40, 32, 28, 512]
cnn.top_layer.shape: [40, 32, 28, 512]
cnn.top_layer.shape: [40, 32, 28, 512]
cnn.top_layer.shape: [40, 32, 28, 512]
cnn.top_layer.shape: [40, 32, 28, 512]
cnn.top_layer.shape: [40, 32, 28, 512]
cnn.top_layer.shape: [40, 16, 14, 1024]
cnn.top_layer.shape: [40, 16, 14, 1024]
cnn.top_layer.shape: [40, 16, 14, 1024]
cnn.top_layer.shape: [40, 16, 14, 1024]
cnn.top_layer.shape: [40, 16, 14, 1024]
cnn.top_layer.shape: [40, 16, 14, 1024]
cnn.top_layer.shape: [40, 16, 14, 1024]
cnn.top_layer.shape: [40, 16, 14, 1024]
cnn.top_layer.shape: [40, 16, 14, 1024]
cnn.top_layer.shape: [40, 16, 14, 1024]
cnn.top_layer.shape: [40, 16, 14, 1024]
cnn.top_layer.shape: [40, 16, 14, 1024]
cnn.top_layer.shape: [40, 8, 7, 2048]
cnn.top_layer.shape: [40, 8, 7, 2048]
cnn.top_layer.shape: [40, 8, 7, 2048]
cnn.top_layer.shape: [40, 8, 7, 2048]
cnn.top_layer.shape: [40, 8, 7, 2048]
shape: cnn.top_layer 11: [40, 8, 7, 2048]
shape: self.top_layer 0000: [40, 8, 7, 2048]
shape: self.top_layer 1111: [40, 8]
shapes: network.top_layer 3: [40, 8]
cnn.top_layer.shape: [40, 8, 7, 2048]
shape: cnn.top_layer 11: [40, 8, 7, 2048]
shape: self.top_layer 0000: [40, 8, 7, 2048]
shape: self.top_layer 1111: [40, 8]
shapes: network.top_layer 3: [40, 8]
Initializing graph
Initializing graph
WARNING:tensorflow:From /data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py:2122: Supervisor.__init__ (from tensorflow.python.training.supervisor) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.MonitoredTrainingSession
W1012 16:46:16.838215 47294311533952 deprecation.py:330] From /data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py:2122: Supervisor.__init__ (from tensorflow.python.training.supervisor) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.MonitoredTrainingSession
WARNING:tensorflow:From /data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py:2122: Supervisor.__init__ (from tensorflow.python.training.supervisor) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.MonitoredTrainingSession
W1012 16:46:16.852382 47465832639872 deprecation.py:330] From /data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py:2122: Supervisor.__init__ (from tensorflow.python.training.supervisor) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.MonitoredTrainingSession
2024-10-12 16:46:17.349106: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties: 
pciBusID: 0000:c1:00.0 name: NVIDIA GeForce RTX 3090 computeCapability: 8.6
coreClock: 1.695GHz coreCount: 82 deviceMemorySize: 23.69GiB deviceMemoryBandwidth: 871.81GiB/s
2024-10-12 16:46:17.350139: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
2024-10-12 16:46:17.350192: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2024-10-12 16:46:17.350199: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      0 
2024-10-12 16:46:17.350205: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 0:   N 
2024-10-12 16:46:17.351380: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1418] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 21899 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce RTX 3090, pci bus id: 0000:c1:00.0, compute capability: 8.6)
2024-10-12 16:46:17.357997: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties: 
pciBusID: 0000:c1:00.0 name: NVIDIA GeForce RTX 3090 computeCapability: 8.6
coreClock: 1.695GHz coreCount: 82 deviceMemorySize: 23.69GiB deviceMemoryBandwidth: 871.81GiB/s
2024-10-12 16:46:17.359147: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
2024-10-12 16:46:17.359201: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2024-10-12 16:46:17.359208: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      0 
2024-10-12 16:46:17.359213: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 0:   N 
2024-10-12 16:46:17.360371: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1418] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 21893 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce RTX 3090, pci bus id: 0000:c1:00.0, compute capability: 8.6)
2024-10-12 16:46:17.909839: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 2800065000 Hz
2024-10-12 16:46:17.909839: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 2800065000 Hz
2024-10-12 16:46:18.497695: I tensorflow/stream_executor/cuda/cuda_driver.cc:789] failed to allocate 21.39G (22963290112 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2024-10-12 16:46:18.498926: I tensorflow/stream_executor/cuda/cuda_driver.cc:789] failed to allocate 19.25G (20666959872 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2024-10-12 16:46:18.499906: I tensorflow/stream_executor/cuda/cuda_driver.cc:789] failed to allocate 17.32G (18600263680 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2024-10-12 16:46:18.500873: I tensorflow/stream_executor/cuda/cuda_driver.cc:789] failed to allocate 15.59G (16740237312 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2024-10-12 16:46:18.501830: I tensorflow/stream_executor/cuda/cuda_driver.cc:789] failed to allocate 14.03G (15066213376 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2024-10-12 16:46:18.502773: I tensorflow/stream_executor/cuda/cuda_driver.cc:789] failed to allocate 12.63G (13559591936 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2024-10-12 16:46:18.503743: I tensorflow/stream_executor/cuda/cuda_driver.cc:789] failed to allocate 11.37G (12203632640 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2024-10-12 16:46:18.504692: I tensorflow/stream_executor/cuda/cuda_driver.cc:789] failed to allocate 10.23G (10983269376 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2024-10-12 16:46:18.505639: I tensorflow/stream_executor/cuda/cuda_driver.cc:789] failed to allocate 9.21G (9884942336 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2024-10-12 16:46:18.506579: I tensorflow/stream_executor/cuda/cuda_driver.cc:789] failed to allocate 8.29G (8896447488 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2024-10-12 16:46:18.507565: I tensorflow/stream_executor/cuda/cuda_driver.cc:789] failed to allocate 7.46G (8006802432 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2024-10-12 16:46:18.508675: I tensorflow/stream_executor/cuda/cuda_driver.cc:789] failed to allocate 6.71G (7206121984 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2024-10-12 16:46:18.509600: I tensorflow/stream_executor/cuda/cuda_driver.cc:789] failed to allocate 6.04G (6485509632 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2024-10-12 16:46:18.510529: I tensorflow/stream_executor/cuda/cuda_driver.cc:789] failed to allocate 5.44G (5836958720 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2024-10-12 16:46:18.511452: I tensorflow/stream_executor/cuda/cuda_driver.cc:789] failed to allocate 4.89G (5253262848 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2024-10-12 16:46:18.512381: I tensorflow/stream_executor/cuda/cuda_driver.cc:789] failed to allocate 4.40G (4727936512 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2024-10-12 16:46:18.513313: I tensorflow/stream_executor/cuda/cuda_driver.cc:789] failed to allocate 3.96G (4255142656 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2024-10-12 16:46:18.514240: I tensorflow/stream_executor/cuda/cuda_driver.cc:789] failed to allocate 3.57G (3829628416 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2024-10-12 16:46:18.515212: I tensorflow/stream_executor/cuda/cuda_driver.cc:789] failed to allocate 3.21G (3446665472 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2024-10-12 16:46:18.516207: I tensorflow/stream_executor/cuda/cuda_driver.cc:789] failed to allocate 2.89G (3101998848 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2024-10-12 16:46:18.517147: I tensorflow/stream_executor/cuda/cuda_driver.cc:789] failed to allocate 2.60G (2791798784 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2024-10-12 16:46:18.518081: I tensorflow/stream_executor/cuda/cuda_driver.cc:789] failed to allocate 2.34G (2512618752 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2024-10-12 16:46:18.519026: I tensorflow/stream_executor/cuda/cuda_driver.cc:789] failed to allocate 2.11G (2261356800 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2024-10-12 16:46:18.519991: I tensorflow/stream_executor/cuda/cuda_driver.cc:789] failed to allocate 1.89G (2035221248 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2024-10-12 16:46:18.520925: I tensorflow/stream_executor/cuda/cuda_driver.cc:789] failed to allocate 1.71G (1831699200 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2024-10-12 16:46:18.521885: I tensorflow/stream_executor/cuda/cuda_driver.cc:789] failed to allocate 1.54G (1648529408 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
INFO:tensorflow:Running local_init_op.
I1012 16:46:18.560135 47294311533952 session_manager.py:531] Running local_init_op.
INFO:tensorflow:Running local_init_op.
I1012 16:46:18.592209 47465832639872 session_manager.py:531] Running local_init_op.
INFO:tensorflow:Done running local_init_op.
I1012 16:46:18.716236 47294311533952 session_manager.py:534] Done running local_init_op.
INFO:tensorflow:Done running local_init_op.
I1012 16:46:18.741512 47465832639872 session_manager.py:534] Done running local_init_op.
Running warm up
Running warm up
2024-10-12 16:46:23.092026: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudnn.so.8
2024-10-12 16:46:23.092035: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudnn.so.8
2024-10-12 16:46:23.449285: E tensorflow/stream_executor/cuda/cuda_dnn.cc:364] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2024-10-12 16:46:23.451947: E tensorflow/stream_executor/cuda/cuda_dnn.cc:364] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2024-10-12 16:46:23.460801: E tensorflow/stream_executor/cuda/cuda_dnn.cc:364] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2024-10-12 16:46:23.463187: E tensorflow/stream_executor/cuda/cuda_dnn.cc:364] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.UnknownError'>, 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node tower_0/v/cg/conv2d/Conv2D (defined at data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/convnet_builder.py:110) ]]
	 [[main_fetch_group/_576]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node tower_0/v/cg/conv2d/Conv2D (defined at data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/convnet_builder.py:110) ]]
0 successful operations.
0 derived errors ignored.

Errors may have originated from an input operation.
Input Source operations connected to node tower_0/v/cg/conv2d/Conv2D:
 tower_0/v/cg/Pad (defined at data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/convnet_builder.py:178)

Input Source operations connected to node tower_0/v/cg/conv2d/Conv2D:
 tower_0/v/cg/Pad (defined at data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/convnet_builder.py:178)

Original stack trace for 'tower_0/v/cg/conv2d/Conv2D':
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py", line 64, in <module>
    app.run(main)  # Raises error on invalid flags, unlike tf.app.run()
  File "HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py", line 56, in main
    bench.run()
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 1755, in run
    return self._benchmark_train()
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 1934, in _benchmark_train
    build_result = self._build_graph()
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 1968, in _build_graph
    (input_producer_op, enqueue_ops, fetches) = self._build_model()
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 2668, in _build_model
    results = self.add_forward_pass_and_gradients(
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 3207, in add_forward_pass_and_gradients
    outputs = maybe_compile(forward_pass_and_gradients, self.params)
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 3401, in maybe_compile
    return computation()
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 3058, in forward_pass_and_gradients
    build_network_result = self.model.build_network(
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/models/model.py", line 266, in build_network
    self.add_inference(network)
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/models/resnet_model.py", line 311, in add_inference
    cnn.conv(64, 7, 7, 2, 2, mode='SAME_RESNET', use_batch_norm=True)
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/convnet_builder.py", line 179, in conv
    conv = self._conv2d_impl(input_layer, num_channels_in,
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/convnet_builder.py", line 110, in _conv2d_impl
    return keras_layers.Conv2D(filters, kernel_size, strides,
  File "HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/keras/engine/base_layer_v1.py", line 783, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/keras/layers/convolutional.py", line 249, in call
    outputs = self._convolution_op(inputs, self.kernel)
  File "HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/util/dispatch.py", line 206, in wrapper
    return target(*args, **kwargs)
  File "HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/ops/nn_ops.py", line 1012, in convolution_v2
    return convolution_internal(
  File "HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/ops/nn_ops.py", line 1142, in convolution_internal
    return op(
  File "HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/ops/nn_ops.py", line 2596, in _conv2d_expanded_batch
    return gen_nn_ops.conv2d(
  File "HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 969, in conv2d
    _, _, _op, _outputs = _op_def_library._apply_op_helper(
  File "HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/framework/op_def_library.py", line 748, in _apply_op_helper
    op = g._create_op_internal(op_type_name, inputs, dtypes=None,
  File "HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 3557, in _create_op_internal
    ret = Operation(
  File "HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 2045, in __init__
    self._traceback = tf_stack.extract_stack_for_node(self._c_op)

I1012 16:46:23.920786 47465832639872 coordinator.py:222] Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.UnknownError'>, 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node tower_0/v/cg/conv2d/Conv2D (defined at data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/convnet_builder.py:110) ]]
	 [[main_fetch_group/_576]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node tower_0/v/cg/conv2d/Conv2D (defined at data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/convnet_builder.py:110) ]]
0 successful operations.
0 derived errors ignored.

Errors may have originated from an input operation.
Input Source operations connected to node tower_0/v/cg/conv2d/Conv2D:
 tower_0/v/cg/Pad (defined at data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/convnet_builder.py:178)

Input Source operations connected to node tower_0/v/cg/conv2d/Conv2D:
 tower_0/v/cg/Pad (defined at data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/convnet_builder.py:178)

Original stack trace for 'tower_0/v/cg/conv2d/Conv2D':
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py", line 64, in <module>
    app.run(main)  # Raises error on invalid flags, unlike tf.app.run()
  File "HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py", line 56, in main
    bench.run()
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 1755, in run
    return self._benchmark_train()
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 1934, in _benchmark_train
    build_result = self._build_graph()
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 1968, in _build_graph
    (input_producer_op, enqueue_ops, fetches) = self._build_model()
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 2668, in _build_model
    results = self.add_forward_pass_and_gradients(
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 3207, in add_forward_pass_and_gradients
    outputs = maybe_compile(forward_pass_and_gradients, self.params)
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 3401, in maybe_compile
    return computation()
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 3058, in forward_pass_and_gradients
    build_network_result = self.model.build_network(
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/models/model.py", line 266, in build_network
    self.add_inference(network)
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/models/resnet_model.py", line 311, in add_inference
    cnn.conv(64, 7, 7, 2, 2, mode='SAME_RESNET', use_batch_norm=True)
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/convnet_builder.py", line 179, in conv
    conv = self._conv2d_impl(input_layer, num_channels_in,
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/convnet_builder.py", line 110, in _conv2d_impl
    return keras_layers.Conv2D(filters, kernel_size, strides,
  File "HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/keras/engine/base_layer_v1.py", line 783, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/keras/layers/convolutional.py", line 249, in call
    outputs = self._convolution_op(inputs, self.kernel)
  File "HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/util/dispatch.py", line 206, in wrapper
    return target(*args, **kwargs)
  File "HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/ops/nn_ops.py", line 1012, in convolution_v2
    return convolution_internal(
  File "HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/ops/nn_ops.py", line 1142, in convolution_internal
    return op(
  File "HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/ops/nn_ops.py", line 2596, in _conv2d_expanded_batch
    return gen_nn_ops.conv2d(
  File "HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 969, in conv2d
    _, _, _op, _outputs = _op_def_library._apply_op_helper(
  File "HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/framework/op_def_library.py", line 748, in _apply_op_helper
    op = g._create_op_internal(op_type_name, inputs, dtypes=None,
  File "HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 3557, in _create_op_internal
    ret = Operation(
  File "HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 2045, in __init__
    self._traceback = tf_stack.extract_stack_for_node(self._c_op)

INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.UnknownError'>, 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node tower_0/v/cg/conv2d/Conv2D (defined at data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/convnet_builder.py:110) ]]
	 [[main_fetch_group/_576]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node tower_0/v/cg/conv2d/Conv2D (defined at data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/convnet_builder.py:110) ]]
0 successful operations.
0 derived errors ignored.

Errors may have originated from an input operation.
Input Source operations connected to node tower_0/v/cg/conv2d/Conv2D:
 tower_0/v/cg/Pad (defined at data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/convnet_builder.py:178)

Input Source operations connected to node tower_0/v/cg/conv2d/Conv2D:
 tower_0/v/cg/Pad (defined at data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/convnet_builder.py:178)

Original stack trace for 'tower_0/v/cg/conv2d/Conv2D':
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py", line 64, in <module>
    app.run(main)  # Raises error on invalid flags, unlike tf.app.run()
  File "HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py", line 56, in main
    bench.run()
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 1755, in run
    return self._benchmark_train()
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 1934, in _benchmark_train
    build_result = self._build_graph()
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 1968, in _build_graph
    (input_producer_op, enqueue_ops, fetches) = self._build_model()
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 2668, in _build_model
    results = self.add_forward_pass_and_gradients(
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 3207, in add_forward_pass_and_gradients
    outputs = maybe_compile(forward_pass_and_gradients, self.params)
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 3401, in maybe_compile
    return computation()
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 3058, in forward_pass_and_gradients
    build_network_result = self.model.build_network(
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/models/model.py", line 266, in build_network
    self.add_inference(network)
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/models/resnet_model.py", line 311, in add_inference
    cnn.conv(64, 7, 7, 2, 2, mode='SAME_RESNET', use_batch_norm=True)
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/convnet_builder.py", line 179, in conv
    conv = self._conv2d_impl(input_layer, num_channels_in,
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/convnet_builder.py", line 110, in _conv2d_impl
    return keras_layers.Conv2D(filters, kernel_size, strides,
  File "HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/keras/engine/base_layer_v1.py", line 783, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/keras/layers/convolutional.py", line 249, in call
    outputs = self._convolution_op(inputs, self.kernel)
  File "HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/util/dispatch.py", line 206, in wrapper
    return target(*args, **kwargs)
  File "HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/ops/nn_ops.py", line 1012, in convolution_v2
    return convolution_internal(
  File "HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/ops/nn_ops.py", line 1142, in convolution_internal
    return op(
  File "HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/ops/nn_ops.py", line 2596, in _conv2d_expanded_batch
    return gen_nn_ops.conv2d(
  File "HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 969, in conv2d
    _, _, _op, _outputs = _op_def_library._apply_op_helper(
  File "HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/framework/op_def_library.py", line 748, in _apply_op_helper
    op = g._create_op_internal(op_type_name, inputs, dtypes=None,
  File "HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 3557, in _create_op_internal
    ret = Operation(
  File "HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 2045, in __init__
    self._traceback = tf_stack.extract_stack_for_node(self._c_op)

I1012 16:46:23.921613 47294311533952 coordinator.py:222] Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.UnknownError'>, 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node tower_0/v/cg/conv2d/Conv2D (defined at data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/convnet_builder.py:110) ]]
	 [[main_fetch_group/_576]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node tower_0/v/cg/conv2d/Conv2D (defined at data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/convnet_builder.py:110) ]]
0 successful operations.
0 derived errors ignored.

Errors may have originated from an input operation.
Input Source operations connected to node tower_0/v/cg/conv2d/Conv2D:
 tower_0/v/cg/Pad (defined at data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/convnet_builder.py:178)

Input Source operations connected to node tower_0/v/cg/conv2d/Conv2D:
 tower_0/v/cg/Pad (defined at data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/convnet_builder.py:178)

Original stack trace for 'tower_0/v/cg/conv2d/Conv2D':
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py", line 64, in <module>
    app.run(main)  # Raises error on invalid flags, unlike tf.app.run()
  File "HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py", line 56, in main
    bench.run()
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 1755, in run
    return self._benchmark_train()
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 1934, in _benchmark_train
    build_result = self._build_graph()
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 1968, in _build_graph
    (input_producer_op, enqueue_ops, fetches) = self._build_model()
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 2668, in _build_model
    results = self.add_forward_pass_and_gradients(
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 3207, in add_forward_pass_and_gradients
    outputs = maybe_compile(forward_pass_and_gradients, self.params)
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 3401, in maybe_compile
    return computation()
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 3058, in forward_pass_and_gradients
    build_network_result = self.model.build_network(
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/models/model.py", line 266, in build_network
    self.add_inference(network)
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/models/resnet_model.py", line 311, in add_inference
    cnn.conv(64, 7, 7, 2, 2, mode='SAME_RESNET', use_batch_norm=True)
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/convnet_builder.py", line 179, in conv
    conv = self._conv2d_impl(input_layer, num_channels_in,
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/convnet_builder.py", line 110, in _conv2d_impl
    return keras_layers.Conv2D(filters, kernel_size, strides,
  File "HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/keras/engine/base_layer_v1.py", line 783, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/keras/layers/convolutional.py", line 249, in call
    outputs = self._convolution_op(inputs, self.kernel)
  File "HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/util/dispatch.py", line 206, in wrapper
    return target(*args, **kwargs)
  File "HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/ops/nn_ops.py", line 1012, in convolution_v2
    return convolution_internal(
  File "HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/ops/nn_ops.py", line 1142, in convolution_internal
    return op(
  File "HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/ops/nn_ops.py", line 2596, in _conv2d_expanded_batch
    return gen_nn_ops.conv2d(
  File "HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 969, in conv2d
    _, _, _op, _outputs = _op_def_library._apply_op_helper(
  File "HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/framework/op_def_library.py", line 748, in _apply_op_helper
    op = g._create_op_internal(op_type_name, inputs, dtypes=None,
  File "HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 3557, in _create_op_internal
    ret = Operation(
  File "HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 2045, in __init__
    self._traceback = tf_stack.extract_stack_for_node(self._c_op)

Traceback (most recent call last):
  File "/HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/client/session.py", line 1375, in _do_call
Traceback (most recent call last):
  File "/HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/client/session.py", line 1375, in _do_call
    return fn(*args)
  File "/HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/client/session.py", line 1359, in _run_fn
    return fn(*args)
  File "/HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/client/session.py", line 1359, in _run_fn
    return self._call_tf_sessionrun(options, feed_dict, fetch_list,
  File "/HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/client/session.py", line 1451, in _call_tf_sessionrun
    return self._call_tf_sessionrun(options, feed_dict, fetch_list,
  File "/HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/client/session.py", line 1451, in _call_tf_sessionrun
    return tf_session.TF_SessionRun_wrapper(self._session, options, feed_dict,
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node tower_0/v/cg/conv2d/Conv2D}}]]
	 [[main_fetch_group/_576]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node tower_0/v/cg/conv2d/Conv2D}}]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py", line 64, in <module>
    return tf_session.TF_SessionRun_wrapper(self._session, options, feed_dict,
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node tower_0/v/cg/conv2d/Conv2D}}]]
	 [[main_fetch_group/_576]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node tower_0/v/cg/conv2d/Conv2D}}]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
    app.run(main)  # Raises error on invalid flags, unlike tf.app.run()
  File "/data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py", line 64, in <module>
  File "/HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/absl/app.py", line 312, in run
    app.run(main)  # Raises error on invalid flags, unlike tf.app.run()
  File "/HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/absl/app.py", line 258, in _run_main
    _run_main(main, args)
  File "/HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py", line 56, in main
    sys.exit(main(argv))
  File "/data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py", line 56, in main
    bench.run()
  File "/data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 1755, in run
    bench.run()
  File "/data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 1755, in run
    return self._benchmark_train()
  File "/data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 1943, in _benchmark_train
    return self._benchmark_train()
  File "/data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 1943, in _benchmark_train
    return self._benchmark_graph(result_to_benchmark, eval_build_results)
  File "/data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 2164, in _benchmark_graph
    return self._benchmark_graph(result_to_benchmark, eval_build_results)
  File "/data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 2164, in _benchmark_graph
    stats = self.benchmark_with_session(
  File "/data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 2293, in benchmark_with_session
    stats = self.benchmark_with_session(
  File "/data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 2293, in benchmark_with_session
    (summary_str, last_average_loss) = benchmark_one_step(
  File "/data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 821, in benchmark_one_step
    results = sess.run(fetches, options=run_options, run_metadata=run_metadata)
  File "/HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/client/session.py", line 967, in run
    (summary_str, last_average_loss) = benchmark_one_step(
  File "/data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 821, in benchmark_one_step
    result = self._run(None, fetches, feed_dict, options_ptr,
  File "/HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/client/session.py", line 1190, in _run
    results = sess.run(fetches, options=run_options, run_metadata=run_metadata)
  File "/HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/client/session.py", line 967, in run
    result = self._run(None, fetches, feed_dict, options_ptr,
  File "/HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/client/session.py", line 1190, in _run
    results = self._do_run(handle, final_targets, final_fetches,
  File "/HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/client/session.py", line 1368, in _do_run
    results = self._do_run(handle, final_targets, final_fetches,
  File "/HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/client/session.py", line 1368, in _do_run
    return self._do_call(_run_fn, feeds, fetches, targets, options,
  File "/HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/client/session.py", line 1394, in _do_call
    return self._do_call(_run_fn, feeds, fetches, targets, options,
  File "/HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/client/session.py", line 1394, in _do_call
    raise type(e)(node_def, op, message)
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node tower_0/v/cg/conv2d/Conv2D (defined at data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/convnet_builder.py:110) ]]
	 [[main_fetch_group/_576]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node tower_0/v/cg/conv2d/Conv2D (defined at data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/convnet_builder.py:110) ]]
0 successful operations.
0 derived errors ignored.

Errors may have originated from an input operation.
Input Source operations connected to node tower_0/v/cg/conv2d/Conv2D:
 tower_0/v/cg/Pad (defined at data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/convnet_builder.py:178)

Input Source operations connected to node tower_0/v/cg/conv2d/Conv2D:
 tower_0/v/cg/Pad (defined at data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/convnet_builder.py:178)

Original stack trace for 'tower_0/v/cg/conv2d/Conv2D':
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py", line 64, in <module>
    app.run(main)  # Raises error on invalid flags, unlike tf.app.run()
  File "HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py", line 56, in main
    bench.run()
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 1755, in run
    return self._benchmark_train()
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 1934, in _benchmark_train
    build_result = self._build_graph()
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 1968, in _build_graph
    (input_producer_op, enqueue_ops, fetches) = self._build_model()
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 2668, in _build_model
    results = self.add_forward_pass_and_gradients(
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 3207, in add_forward_pass_and_gradients
    outputs = maybe_compile(forward_pass_and_gradients, self.params)
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 3401, in maybe_compile
    return computation()
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 3058, in forward_pass_and_gradients
    build_network_result = self.model.build_network(
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/models/model.py", line 266, in build_network
    self.add_inference(network)
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/models/resnet_model.py", line 311, in add_inference
    cnn.conv(64, 7, 7, 2, 2, mode='SAME_RESNET', use_batch_norm=True)
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/convnet_builder.py", line 179, in conv
    conv = self._conv2d_impl(input_layer, num_channels_in,
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/convnet_builder.py", line 110, in _conv2d_impl
    return keras_layers.Conv2D(filters, kernel_size, strides,
  File "HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/keras/engine/base_layer_v1.py", line 783, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/keras/layers/convolutional.py", line 249, in call
    outputs = self._convolution_op(inputs, self.kernel)
  File "HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/util/dispatch.py", line 206, in wrapper
    return target(*args, **kwargs)
  File "HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/ops/nn_ops.py", line 1012, in convolution_v2
    return convolution_internal(
  File "HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/ops/nn_ops.py", line 1142, in convolution_internal
    return op(
  File "HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/ops/nn_ops.py", line 2596, in _conv2d_expanded_batch
    return gen_nn_ops.conv2d(
  File "HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 969, in conv2d
    _, _, _op, _outputs = _op_def_library._apply_op_helper(
  File "HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/framework/op_def_library.py", line 748, in _apply_op_helper
    op = g._create_op_internal(op_type_name, inputs, dtypes=None,
  File "HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 3557, in _create_op_internal
    ret = Operation(
  File "HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 2045, in __init__
    self._traceback = tf_stack.extract_stack_for_node(self._c_op)

tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node tower_0/v/cg/conv2d/Conv2D (defined at data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/convnet_builder.py:110) ]]
	 [[main_fetch_group/_576]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node tower_0/v/cg/conv2d/Conv2D (defined at data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/convnet_builder.py:110) ]]
0 successful operations.
0 derived errors ignored.

Errors may have originated from an input operation.
Input Source operations connected to node tower_0/v/cg/conv2d/Conv2D:
 tower_0/v/cg/Pad (defined at data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/convnet_builder.py:178)

Input Source operations connected to node tower_0/v/cg/conv2d/Conv2D:
 tower_0/v/cg/Pad (defined at data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/convnet_builder.py:178)

Original stack trace for 'tower_0/v/cg/conv2d/Conv2D':
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py", line 64, in <module>
    app.run(main)  # Raises error on invalid flags, unlike tf.app.run()
  File "HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py", line 56, in main
    bench.run()
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 1755, in run
    return self._benchmark_train()
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 1934, in _benchmark_train
    build_result = self._build_graph()
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 1968, in _build_graph
    (input_producer_op, enqueue_ops, fetches) = self._build_model()
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 2668, in _build_model
    results = self.add_forward_pass_and_gradients(
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 3207, in add_forward_pass_and_gradients
    outputs = maybe_compile(forward_pass_and_gradients, self.params)
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 3401, in maybe_compile
    return computation()
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 3058, in forward_pass_and_gradients
    build_network_result = self.model.build_network(
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/models/model.py", line 266, in build_network
    self.add_inference(network)
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/models/resnet_model.py", line 311, in add_inference
    cnn.conv(64, 7, 7, 2, 2, mode='SAME_RESNET', use_batch_norm=True)
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/convnet_builder.py", line 179, in conv
    conv = self._conv2d_impl(input_layer, num_channels_in,
  File "data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/convnet_builder.py", line 110, in _conv2d_impl
    return keras_layers.Conv2D(filters, kernel_size, strides,
  File "HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/keras/engine/base_layer_v1.py", line 783, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/keras/layers/convolutional.py", line 249, in call
    outputs = self._convolution_op(inputs, self.kernel)
  File "HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/util/dispatch.py", line 206, in wrapper
    return target(*args, **kwargs)
  File "HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/ops/nn_ops.py", line 1012, in convolution_v2
    return convolution_internal(
  File "HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/ops/nn_ops.py", line 1142, in convolution_internal
    return op(
  File "HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/ops/nn_ops.py", line 2596, in _conv2d_expanded_batch
    return gen_nn_ops.conv2d(
  File "HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 969, in conv2d
    _, _, _op, _outputs = _op_def_library._apply_op_helper(
  File "HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/framework/op_def_library.py", line 748, in _apply_op_helper
    op = g._create_op_internal(op_type_name, inputs, dtypes=None,
  File "HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 3557, in _create_op_internal
    ret = Operation(
  File "HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 2045, in __init__
    self._traceback = tf_stack.extract_stack_for_node(self._c_op)

--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[16443,1],1]
  Exit code:    1
--------------------------------------------------------------------------
