[arg] [0]=/HOME/scz1075/.conda/envs/kungfu/bin/python
[arg] [1]=/HOME/scz1075/.local/bin/kungfu-run
[arg] [2]=-np
[arg] [3]=2
[arg] [4]=/HOME/scz1075/.conda/envs/kungfu/bin/python3
[arg] [5]=tf_cnn_benchmarks.py
[arg] [6]=--batch_size=64
[arg] [7]=--model=resnet50
[arg] [8]=--optimizer=momentum
[arg] [9]=--variable_update=kungfu
[arg] [10]=--kungfu_option=sync_sgd
[arg] [11]=--nodistortions
[arg] [12]=--num_gpus=1
[arg] [13]=--num_epochs=90
[arg] [14]=--weight_decay=1e-4
[nic] [0] lo :: 127.0.0.1/8, ::1/128
[nic] [1] enp39s0f3u1u2c2 :: 
[nic] [2] eno1 :: 10.254.24.35/22, fe80::3eec:efff:fe05:6b06/64
[nic] [3] eno2 :: 
[nic] [4] enp195s0f0 :: 
[nic] [5] enp195s0f1 :: 
[nic] [6] bond0 :: 10.254.128.35/24, fe80::9a03:9bff:fe48:e600/64
[cuda-env]: CUDA_PATH=/data/apps/cuda/11.1
[cuda-env]: CUDA_HOME=/data/apps/cuda/11.1
[cuda-env]: CUDA_VISIBLE_DEVICES=0
[cuda-env]: CUDA_ROOT=/data/apps/cuda/11.1
[W] CUDA_VISIBLE_DEVICES=0 is not enough for local rank 1
[I] will parallel run 2 instances of /HOME/scz1075/.conda/envs/kungfu/bin/python3 with ["tf_cnn_benchmarks.py" "--batch_size=64" "--model=resnet50" "--optimizer=momentum" "--variable_update=kungfu" "--kungfu_option=sync_sgd" "--nodistortions" "--num_gpus=1" "--num_epochs=90" "--weight_decay=1e-4"]
[[1;34m127.0.0.1.10001[m::[1;35mstderr[m] 2024-10-12 15:47:57.837992: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
[[1;32m127.0.0.1.10000[m::[1;35mstderr[m] 2024-10-12 15:47:57.837988: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
[[1;32m127.0.0.1.10000[m::stdout] KungFu does not require to call init()
[[1;34m127.0.0.1.10001[m::stdout] KungFu does not require to call init()
[[1;34m127.0.0.1.10001[m::[1;35mstderr[m] 2024-10-12 15:48:36.312861: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
[[1;32m127.0.0.1.10000[m::[1;35mstderr[m] 2024-10-12 15:48:36.312861: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
[[1;34m127.0.0.1.10001[m::[1;35mstderr[m] To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
[[1;32m127.0.0.1.10000[m::[1;35mstderr[m] To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
[[1;32m127.0.0.1.10000[m::[1;35mstderr[m] 2024-10-12 15:48:36.394269: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcuda.so.1
[[1;34m127.0.0.1.10001[m::[1;35mstderr[m] 2024-10-12 15:48:36.394269: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcuda.so.1
[[1;34m127.0.0.1.10001[m::[1;35mstderr[m] 2024-10-12 15:48:36.428551: E tensorflow/stream_executor/cuda/cuda_driver.cc:328] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
[[1;34m127.0.0.1.10001[m::[1;35mstderr[m] 2024-10-12 15:48:36.430433: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: g0018
[[1;34m127.0.0.1.10001[m::[1;35mstderr[m] 2024-10-12 15:48:36.431423: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: g0018
[[1;34m127.0.0.1.10001[m::[1;35mstderr[m] 2024-10-12 15:48:36.432485: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 535.104.5
[[1;34m127.0.0.1.10001[m::[1;35mstderr[m] 2024-10-12 15:48:36.433080: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 535.104.5
[[1;34m127.0.0.1.10001[m::[1;35mstderr[m] 2024-10-12 15:48:36.433095: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:310] kernel version seems to match DSO: 535.104.5
[[1;32m127.0.0.1.10000[m::[1;35mstderr[m] 2024-10-12 15:48:36.435754: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties: 
[[1;32m127.0.0.1.10000[m::[1;35mstderr[m] pciBusID: 0000:e1:00.0 name: NVIDIA GeForce RTX 3090 computeCapability: 8.6
[[1;32m127.0.0.1.10000[m::[1;35mstderr[m] coreClock: 1.695GHz coreCount: 82 deviceMemorySize: 23.69GiB deviceMemoryBandwidth: 871.81GiB/s
[[1;32m127.0.0.1.10000[m::[1;35mstderr[m] 2024-10-12 15:48:36.437757: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
[[1;32m127.0.0.1.10000[m::[1;35mstderr[m] 2024-10-12 15:48:36.443290: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublas.so.11
[[1;32m127.0.0.1.10000[m::[1;35mstderr[m] 2024-10-12 15:48:36.443330: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublasLt.so.11
[[1;32m127.0.0.1.10000[m::[1;35mstderr[m] 2024-10-12 15:48:36.445998: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcufft.so.10
[[1;34m127.0.0.1.10001[m::[1;35mstderr[m] Traceback (most recent call last):
[[1;34m127.0.0.1.10001[m::[1;35mstderr[m]   File "/data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py", line 64, in <module>
[[1;32m127.0.0.1.10000[m::[1;35mstderr[m] 2024-10-12 15:48:36.449015: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcurand.so.10
[[1;34m127.0.0.1.10001[m::[1;35mstderr[m]     app.run(main)  # Raises error on invalid flags, unlike tf.app.run()
[[1;34m127.0.0.1.10001[m::[1;35mstderr[m]   File "/HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/absl/app.py", line 312, in run
[[1;34m127.0.0.1.10001[m::[1;35mstderr[m]     _run_main(main, args)
[[1;34m127.0.0.1.10001[m::[1;35mstderr[m]   File "/HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/absl/app.py", line 258, in _run_main
[[1;34m127.0.0.1.10001[m::[1;35mstderr[m]     sys.exit(main(argv))
[[1;34m127.0.0.1.10001[m::[1;35mstderr[m]   File "/data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py", line 50, in main
[[1;34m127.0.0.1.10001[m::[1;35mstderr[m]     bench = benchmark_cnn.BenchmarkCNN(params)
[[1;34m127.0.0.1.10001[m::[1;35mstderr[m]   File "/data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 1409, in __init__
[[1;34m127.0.0.1.10001[m::[1;35mstderr[m]     from kungfu import current_cluster_size  # pylint: disable=g-import-not-at-top
[[1;34m127.0.0.1.10001[m::[1;35mstderr[m] ImportError: cannot import name 'current_cluster_size' from 'kungfu' (/HOME/scz1075/.local/lib/python3.9/site-packages/kungfu/__init__.py)
[[1;32m127.0.0.1.10000[m::[1;35mstderr[m] 2024-10-12 15:48:36.851112: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcusolver.so.11
[[1;32m127.0.0.1.10000[m::[1;35mstderr[m] 2024-10-12 15:48:36.953420: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcusparse.so.11
[[1;32m127.0.0.1.10000[m::[1;35mstderr[m] 2024-10-12 15:48:36.999991: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudnn.so.8
[[1;32m127.0.0.1.10000[m::[1;35mstderr[m] 2024-10-12 15:48:37.003417: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
[[1;32m127.0.0.1.10000[m::[1;35mstderr[m] 2024-10-12 15:48:37.003452: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
[[1;32m127.0.0.1.10000[m::[1;35mstderr[m] 2024-10-12 15:48:38.844708: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
[[1;32m127.0.0.1.10000[m::[1;35mstderr[m] 2024-10-12 15:48:38.844766: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      0 
[[1;32m127.0.0.1.10000[m::[1;35mstderr[m] 2024-10-12 15:48:38.844774: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 0:   N 
[[1;32m127.0.0.1.10000[m::[1;35mstderr[m] 2024-10-12 15:48:38.848344: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1418] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 22300 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce RTX 3090, pci bus id: 0000:e1:00.0, compute capability: 8.6)
[[1;32m127.0.0.1.10000[m::[1;35mstderr[m] Traceback (most recent call last):
[[1;32m127.0.0.1.10000[m::[1;35mstderr[m]   File "/data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py", line 64, in <module>
[[1;32m127.0.0.1.10000[m::[1;35mstderr[m]     app.run(main)  # Raises error on invalid flags, unlike tf.app.run()
[[1;32m127.0.0.1.10000[m::[1;35mstderr[m]   File "/HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/absl/app.py", line 312, in run
[[1;32m127.0.0.1.10000[m::[1;35mstderr[m]     _run_main(main, args)
[[1;32m127.0.0.1.10000[m::[1;35mstderr[m]   File "/HOME/scz1075/.conda/envs/kungfu/lib/python3.9/site-packages/absl/app.py", line 258, in _run_main
[[1;32m127.0.0.1.10000[m::[1;35mstderr[m]     sys.exit(main(argv))
[[1;32m127.0.0.1.10000[m::[1;35mstderr[m]   File "/data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py", line 50, in main
[[1;32m127.0.0.1.10000[m::[1;35mstderr[m]     bench = benchmark_cnn.BenchmarkCNN(params)
[[1;32m127.0.0.1.10000[m::[1;35mstderr[m]   File "/data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 1409, in __init__
[[1;32m127.0.0.1.10000[m::[1;35mstderr[m]     from kungfu import current_cluster_size  # pylint: disable=g-import-not-at-top
[[1;32m127.0.0.1.10000[m::[1;35mstderr[m] ImportError: cannot import name 'current_cluster_size' from 'kungfu' (/HOME/scz1075/.local/lib/python3.9/site-packages/kungfu/__init__.py)
[1;35m[E][m #<127.0.0.1.10001> exited with error: exit status 1
[1;35m[E][m #<127.0.0.1.10000> exited with error: exit status 1
[I] all 2/2 local peers finished, took 57.975405475s
exit on error: 2 tasks failed at 47911873313291:/data/run01/scz1075/KungFu/srcs/go/kungfu/runner/simple.go:19
